<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXd0gc3b\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXd0gc3b/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerXd0gc3b.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerXd0gc3b\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerXd0gc3b\appAppKernelProdContainer([
    'container.build_hash' => 'Xd0gc3b',
    'container.build_id' => 'dc1ae128',
    'container.build_time' => 1694290888,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXd0gc3b');
