<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFx9MS5z\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFx9MS5z/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerFx9MS5z.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerFx9MS5z\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerFx9MS5z\appAppKernelProdContainer([
    'container.build_hash' => 'Fx9MS5z',
    'container.build_id' => '1897830e',
    'container.build_time' => 1692358611,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFx9MS5z');
